#!/bin/sh

# clear if parameter allow
if [[ $1 == "c" ]];then
	clear
fi

# remove old output file if it exists
if [[ -f ./app.out ]];then
	rm ./app.out
fi

# Compile program
g++ -std=c++11 main.cpp -o app.out

# run out file if compilatoin successful
if [[ -f ./app.out ]];then
	./app.out
fi

# Print a newline
# echo