#!/bin/sh

# clear if parameter allow
if [[ $1 == "c" ]];then
	clear
fi

# remove old output file if it exists
if [[ -f $main.out ]];then
	rm main.out
	echo "Removed old output file\n"
fi

# Compile and run program
g++ main.cpp -o main.out
./main.out

echo