#!/bin/sh

# clear if parameter allow
if [[ $1 == "c" ]];then
	clear
fi

# remove old output file if it exists
if [[ -f ./main.out ]];then
	rm ./main.out
fi

# Compile and run program
g++ main.cpp -o main.out

# run out file if compilatoin successful
if [[ -f ./main.out ]];then
	./main.out
fi

# Print a newline
echo