#!/bin/sh

# clear if parameter allow
if [[ $1 == "c" ]];then
	clear
fi

# remove old output file if it exists
if [[ -f ./q4.out ]];then
	rm ./q4.out
fi

# Compile program
g++ -std=c++11 main-q4.cpp -o q4.out

# run out file if compilatoin successful
if [[ -f ./q4.out ]];then
	./q4.out
fi

# Print a newline
# echo